name: blending
dependencies:
  - python=3.5
  - pip
  - pip:
    - chainer==1.24
    - cupy==2.0 # Don't install if you don't have a CUDA environment
    - numpy
    - scikit-image
    - scipy
